name: .NET Continuous Deployment

on:
  push:
    branches: [ master ]
    paths:
      - src/**
  workflow_dispatch:
permissions:
  contents: write
  packages: write
  id-token: write
jobs:

  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Run Tests
        run: dotnet test --logger GitHubActions ./src/PgfPlotsSdk.sln

  semantic-release:
    permissions: write-all
    needs: test
    name: Create a Package Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Need the full commit history for conventional commit
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Create Nuget Package
        run: dotnet build -c Release ./src/PgfPlotsSdk/PgfPlotsSdk.csproj && dotnet pack -c Release -p:PackageVersion=${{ steps.tag_version.outputs.new_version }} -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg -o . ./src/PgfPlotsSdk/PgfPlotsSdk.csproj
      - name: Upload Package for Publishing
        uses: actions/upload-artifact@v4
        with:
          name: PackedLib
          path: ./*.nupkg
      - name: Upload Symbols for Publishing
        uses: actions/upload-artifact@v4
        with:
          name: PackedSymbols
          path: ./*.snupkg
  
  github-publish:
    permissions:
      packages: write
    needs: semantic-release
    name: Publish to Github
    runs-on: ubuntu-latest
    steps:
      - name: Download built project
        uses: actions/download-artifact@v4
        with:
          name: PackedLib
      - name: Download packed Symbols
        uses: actions/download-artifact@v4
        with:
          name: PackedSymbols
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Push Package to GitHub
        run: dotnet nuget push --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/hughesjs/index.json" --skip-duplicate *.nupkg

  nuget-publish:
    permissions:
      id-token: write
    needs: semantic-release
    name: Publish to Nuget
    runs-on: ubuntu-latest
    steps:
      - name: Download built project
        uses: actions/download-artifact@v4
        with:
          name: PackedLib
      - name: Download packed Symbols
        uses: actions/download-artifact@v4
        with:
          name: PackedSymbols
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Push Package to Nuget
        run: dotnet nuget push --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source "https://api.nuget.org/v3/index.json" --skip-duplicate *.nupkg
